name: Deploy_lemp

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

env:
  AWS_REGION_NAME: "eu-central-1"

jobs:

  CI_part:
    
    runs-on: ubuntu-latest

    steps:
    
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GH_ACTION_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GH_ACTION_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
    
    - name: Create LEMP
      run: |
        echo "${{ secrets.USER_DATA_SCRIPT }}" > user_data.base64.sh
        aws ec2 run-instances --count 1 --image-id ami-0d10f2d3b9ab936a1 \
        --instance-type t2.micro --subnet-id subnet-000c2008b7496a3b7 \
        --associate-public-ip-address \
        --security-group-ids sg-061ddb8453ccbf935 sg-004c28689f21a4a77 --key-name bochinskii_Frankfurt_2 \
        --iam-instance-profile Name=S3ReadOnlyRoleForbochinskii.rocinante \
        --user-data file://user_data.base64.sh \
        --block-device-mappings file://block_device_mappings.json \
        --tag-specifications file://tag_specifications.json
        
        
