name: test

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

env:
  AWS_REGION_NAME: "eu-central-1"

jobs:

  CI_part:
  
    env:
        SSL_CERT: rocinante.crt
        SSL_KEY: rocinante.key

    runs-on: ubuntu-latest

    steps:

    - name: Clone repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GH_ACTION_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GH_ACTION_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
    
    - name: Preper certs
      run: |
        echo "${{ secrets.REAL_KEY }}" > real_rocinante.key
        chmod 0600 real_rocinante.key
    
    - name: Get Variables
      run: |
        IP_ADDRESS=`aws ec2 describe-instances --filters "Name=tag:Name,Values=rocinante" --query "Reservations[*].Instances[*].{IP:PublicIpAddress}" --output text`
        echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.IP_ADDRESS }}
        username: ec2-user
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "configs/*,real_rocinante.cert,real_rocinante.key"
        target: "/home/ec2-user"
